runtime: nodejs12
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
env_variables:
  BUCKET_NAME: "molten-reserve-321412.appspot.com"
  GCLOUD_STORAGE_BUCKET: "molten-reserve-321412.appspot.com"
  GOOGLE_APPLICATION_CREDENTIALS: "App Engine:/gcp-keys.json"
handlers: